export const departments = [
  'Department of Biology',
  'Department of Biochemistry',
  'Department of Genetics',
  'Department of Microbiology',
  'Department of Molecular Biology',
  'Department of Ecology',
  'Department of Marine Biology',
  'Department of Chemistry',
  'Department of Organic Chemistry',
  'Department of Inorganic Chemistry',
  'Department of Physical Chemistry',
  'Department of Analytical Chemistry',
  'Department of Physics',
  'Department of Theoretical Physics',
  'Department of Applied Physics',
  'Department of Astrophysics',
  'Department of Quantum Physics',
  'Department of Geology',
  'Department of Meteorology',
  'Department of Oceanography',
  'Department of Environmental Science',
  'Department of Geophysics',
  'Department of Mathematics',
  'Department of Applied Mathematics',
  'Department of Statistics',
  'Department of Computational Mathematics',
  'Department of Mechanical Engineering',
  'Department of Aerospace Engineering',
  'Department of Automotive Engineering',
  'Department of Industrial Engineering',
  'Department of Electrical Engineering',
  'Department of Electronics Engineering',
  'Department of Telecommunications Engineering',
  'Department of Power Engineering',
  'Department of Civil Engineering',
  'Department of Structural Engineering',
  'Department of Transportation Engineering',
  'Department of Environmental Engineering',
  'Department of Computer Engineering',
  'Department of Software Engineering',
  'Department of Network Engineering',
  'Department of Cybersecurity',
  'Department of English',
  'Department of Comparative Literature',
  'Department of World Literature',
  'Department of Creative Writing',
  'Department of Philosophy',
  'Department of Ethics',
  'Department of Logic',
  'Department of Political Philosophy',
  'Department of History',
  'Department of Ancient History',
  'Department of Modern History',
  'Department of Archaeology',
  'Department of Spanish',
  'Department of French',
  'Department of German',
  'Department of Mandarin',
  'Department of Arabic',
  'Department of Linguistics',
  'Department of Psychology',
  'Department of Clinical Psychology',
  'Department of Developmental Psychology',
  'Department of Cognitive Neuroscience',
  'Department of Sociology',
  'Department of Criminology',
  'Department of Urban Studies',
  'Department of Social Work',
  'Department of Political Science',
  'Department of International Relations',
  'Department of Public Policy',
  'Department of Comparative Politics',
  'Department of Economics',
  'Department of Macroeconomics',
  'Department of Microeconomics',
  'Department of Econometrics',
  'Department of Anthropology',
  'Department of Cultural Anthropology',
  'Department of Archaeology',
  'Department of Social Anthropology',
  'Department of Accounting',
  'Department of Auditing',
  'Department of Financial Reporting',
  'Department of Finance',
  'Department of Investment Management',
  'Department of Financial Planning',
  'Department of Marketing',
  'Department of Consumer Research',
  'Department of Brand Management',
  'Department of Management',
  'Department of Operations Management',
  'Department of Strategic Management',
  'Department of Human Resources',
  'Department of International Business',
  'Department of Global Trade',
  'Department of Cross-Cultural Management',
  'Department of Medicine',
  'Department of Surgery',
  'Department of Pediatrics',
  'Department of Psychiatry',
  'Department of Internal Medicine',
  'Department of Nursing',
  'Department of Clinical Nursing',
  'Department of Public Health Nursing',
  'Department of Pharmacy',
  'Department of Pharmacology',
  'Department of Clinical Pharmacy',
  'Department of Public Health',
  'Department of Epidemiology',
  'Department of Health Policy',
  'Department of Dentistry',
  'Department of Orthodontics',
  'Department of Oral Surgery',
  'Department of Fine Arts',
  'Department of Painting',
  'Department of Sculpture',
  'Department of Photography',
  'Department of Theater',
  'Department of Dance',
  'Department of Music',
  'Department of Film',
  'Department of Graphic Design',
  'Department of Industrial Design',
  'Department of Fashion Design',
  'Department of Interior Design',
  'Department of Film Studies',
  'Department of Media Production',
  'Department of Animation',
  'Department of Computer Science',
  'Department of Artificial Intelligence',
  'Department of Data Science',
  'Department of Software Development',
  'Department of Information Systems',
  'Department of Database Management',
  'Department of IT Security',
  'Department of Cybersecurity',
  'Department of Digital Forensics',
  'Department of Network Security',
  'Department of Public Law',
  'Department of Constitutional Law',
  'Department of Administrative Law',
  'Department of Private Law',
  'Department of Contract Law',
  'Department of Property Law',
  'Department of Corporate Law',
  'Department of Business Law',
  'Department of Financial Law',
  'Department of International Law',
  'Department of Human Rights Law',
  'Department of Trade Law',
];
