export const professionalIndustries = [
    "Information Technology",
    "Software Development",
    "Data Science",
    "Mathematics",
    "Engineering",
    "Physics",
    "Communication and Language Studies",
    "Healthcare",
    "Business and Management",
    "Finance and Accounting",
    "Marketing and Sales",
    "Human Resources",
    "Education",
    "Social Sciences",
    "Law and Legal Services",
    "Creative Arts and Design",
    "Media and Journalism",
    "Hospitality and Tourism",
    "Environmental Sciences",
    "Agriculture and Food Sciences",
    "Pharmaceuticals",
    "Biotechnology",
    "Public Health",
    "Public Policy and Government",
    "Economics",
    "Sociology and Anthropology",
    "Psychology and Mental Health",
    "Political Science",
    "Architecture and Construction",
    "Transportation and Logistics",
    "Energy and Utilities",
    "Telecommunications",
    "Cybersecurity",
    "Aerospace"
  ];
  